import { Recipe } from "../types/recipe";

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Nasi Goreng Spesial",
    image: "https://loremflickr.com/300/400/nasi",
    isFavorite: true,
    ingredients: ["2 piring nasi putih", "2 butir telur", "3 siung bawang putih", "5 buah cabai merah", "100 gram ayam suwir", "2 sdm kecap manis", "1 sdt garam", "1/2 sdt merica", "2 sdm minyak goreng"],
    steps: ["Tumis bawang putih dan cabai merah.", "Masukkan ayam suwir dan telur, aduk hingga matang.", "Tambahkan nasi dan bumbu, aduk rata.", "Sajikan selagi hangat."],
    nutrition: { calories: 450, protein: 20, carbs: 60, fat: 12, fiber: 3 },
  },
  {
    id: "2",
    title: "Mie Goreng Jawa",
    image: "https://loremflickr.com/300/400/noodle",
    isFavorite: true,
    ingredients: ["1 bungkus mie telur", "1 butir telur", "3 siung bawang merah", "1 siung bawang putih", "50 gram ayam", "1 sdm saus tiram", "2 sdm kecap manis", "1/2 sdt garam", "Minyak goreng secukupnya"],
    steps: ["Rebus mie hingga matang, tiriskan.", "Tumis bumbu, masukkan ayam dan telur.", "Masukkan mie dan bumbu lain, aduk rata.", "Sajikan dengan acar."],
    nutrition: { calories: 520, protein: 18, carbs: 70, fat: 15, fiber: 2 },
  },
  {
    id: "3",
    title: "Capcay Kuah",
    image: "https://loremflickr.com/300/400/vegetables",
    isFavorite: true,
    ingredients: ["100 gram wortel", "100 gram brokoli", "50 gram kol", "3 siung bawang putih", "5 bakso sapi", "1 sdm saus tiram", "1 sdm kecap asin", "500 ml air", "Garam dan merica"],
    steps: ["Tumis bawang putih, masukkan sayur dan bakso.", "Tambahkan air dan bumbu, masak hingga matang.", "Sajikan hangat dengan nasi."],
    nutrition: { calories: 300, protein: 12, carbs: 35, fat: 8, fiber: 5 },
  },
  {
    id: "4",
    title: "Ayam Bakar Madu",
    image: "https://loremflickr.com/300/400/chicken",
    isFavorite: true,
    ingredients: ["4 potong ayam", "2 sdm madu", "2 sdm kecap manis", "3 siung bawang putih", "1 sdm air jeruk nipis", "1 sdt garam", "1/2 sdt merica", "Minyak untuk olesan"],
    steps: ["Lumuri ayam dengan bumbu dan diamkan 1 jam.", "Panggang sambil dioles madu dan kecap.", "Bakar hingga matang dan harum.", "Sajikan dengan sambal."],
    nutrition: { calories: 400, protein: 30, carbs: 12, fat: 20, fiber: 1 },
  },
  {
    id: "5",
    title: "Sup Ayam Kampung",
    image: "https://loremflickr.com/300/400/soup",
    isFavorite: false,
    ingredients: ["500 gram ayam kampung", "2 buah wortel", "2 kentang", "1 batang seledri", "2 siung bawang putih", "1 liter air", "Garam dan merica secukupnya"],
    steps: ["Rebus ayam hingga empuk.", "Masukkan sayuran dan bumbu, masak hingga matang.", "Sajikan panas dengan nasi."],
    nutrition: { calories: 380, protein: 25, carbs: 30, fat: 14, fiber: 4 },
  },
  {
    id: "6",
    title: "Tumis Kangkung Terasi",
    image: "https://loremflickr.com/300/400/kangkung",
    isFavorite: false,
    ingredients: ["1 ikat kangkung", "2 siung bawang putih", "3 siung bawang merah", "1 sdt terasi", "3 cabai rawit", "1/2 sdt garam", "2 sdm minyak goreng"],
    steps: ["Tumis bawang dan terasi hingga harum.", "Masukkan cabai dan kangkung, aduk cepat.", "Masak hingga layu dan sajikan segera."],
    nutrition: { calories: 120, protein: 3, carbs: 10, fat: 6, fiber: 2 },
  },
  {
    id: "7",
    title: "Perkedel Kentang",
    image: "https://loremflickr.com/300/400/potato",
    isFavorite: false,
    ingredients: ["500 gram kentang", "2 butir telur", "2 batang daun bawang", "1 siung bawang putih", "1/2 sdt garam", "1/2 sdt merica", "Minyak untuk menggoreng"],
    steps: ["Rebus kentang, haluskan.", "Campur semua bahan, bentuk bulat pipih.", "Goreng hingga kuning keemasan.", "Tiriskan dan sajikan."],
    nutrition: { calories: 250, protein: 6, carbs: 30, fat: 10, fiber: 3 },
  },
  {
    id: "8",
    title: "Sate Tempe Manis",
    image: "https://loremflickr.com/300/400/tempe",
    isFavorite: false,
    ingredients: ["200 gram tempe", "2 sdm kecap manis", "1 siung bawang putih", "1/2 sdt ketumbar bubuk", "Tusuk sate", "Minyak secukupnya"],
    steps: ["Potong tempe, rendam dalam bumbu kecap.", "Tusuk tempe, panggang hingga matang.", "Olesi sisa bumbu sambil dibakar.", "Sajikan dengan sambal kacang."],
    nutrition: { calories: 270, protein: 15, carbs: 15, fat: 16, fiber: 2 },
  },
];
